sudo: required
services: 
    - docker
cache: apt
language: cpp
addons:
  apt:
    packages:
      - help2man
      - lintian
      - cppcheck
      - tree
      - debhelper
      - libudev-dev
      - imagemagick
      - qt5-default
      - libqt5serialport5-dev
matrix:
  include:

  - os: osx
    compiler: clang
    env:
        PLATFORM=osx
        PATH=/Users/travis/local/bin:$PATH
        PYTHONPATH=$PYTHONPATH:$HOME/local/lib/python2.7/site-packages 

  - os: linux
    compiler: g++
    env:
        PLATFORM=linux
        PATH=/home/travis/local/bin:$PATH
        PYTHONPATH=$PYTHONPATH:$HOME/local/lib/python2.7/site-packages

  - os: linux
    compiler: clang
    env:
        PLATFORM=linux
        PATH=/home/travis/local/bin:$PATH
        PYTHONPATH=$PYTHONPATH:$HOME/local/lib/python2.7/site-packages
        QMAKESPEC=linux-clang

install: "./scripts/travis/install.sh"
script:  "./scripts/travis/script.sh"
after_script: "./scripts/travis/after_script.sh"
deploy:
  provider: releases
  api_key:
    secure: wQ4olsxkw3wY/NiL6O5KdpjVHIWxdWx545kYocYUGIOndYXi9a41s5Ne3+UaPWhjqOX/+VWs9vHz6muTg3mgMQapQTmy9IMXdcMfP8gQgHtJzOlJZwfSl43efTws/tg7IJpEfASLfiozvSbXT7hoGDSO+xRmlvSN5Q0lBP2zzZ5JNx616xB7MDQpmRtSct4nMnWhUipHwdeUmGn0AjjgDlvgFXWN3hi7yz2LkG1NmTkAimsM/T58ubZY4KYUv3NV8PduEZPgvnAulC7unykrIkEtT1UIZ+qd2sOWG8qxX18f+pGeWIBlQHRugJmJpU4Lh7Umg6DQ2Q3QjZK1q+QDh7yhM95+T/pJaX4BFvmGhd5PTfe4cD5Idv4FqW3xRomHMQ+MfM+ibz51WbYR9Bn7+FzP3UWNxynIuf61MwPCx6weOpBEZ2lwP8m8jGx+k+gpzk8GvBiQrSzW+YrSsYAR58J6Om07BqcS9lXdsYdRVFHwF2ccwjGBho1NKH1m9zDvdI7mUXkjvczB6jzfqMXK2UxQtDpsZl9iz6TnLtgrALdIRaEUQ9+ZJvdAx+PGykViKgvVWSCyBRL7HZdy+V+V190a7KN2bWg44UXVWca9q9wCcv8WPtNiz9MWk4PprKIHx4O3CLs8nTOJAFidus8Ejvm0L/z3MfX0d0BaIUPelHM=
  file_glob: true
  file: badgehacker-*
  skip_cleanup: true
  on:
    repo: parallaxinc/BadgeHacker
    tags: true
    all_branches: true
