excerpt: Deploy the Parallax Hackable Electronic Badge at your event without ever having to touch
         a line of code.
type: tools

version: 0.8.0
image: https://raw.githubusercontent.com/parallaxinc/BadgeHacker/master/gfx/20000-cut.png
